CREATE OR REPLACE TABLE preprocessed.inat_phenology_pivoted AS

SELECT
    taxonID,
    attribute_label,
    attribute_id,
    value_label,
    value_id,
    count,
    ROUND(CAST(month_1 AS FLOAT) / NULLIF(count, 0),3) AS month_1_density,
    ROUND(CAST(month_2 AS FLOAT) / NULLIF(count, 0),3) AS month_2_density,
    ROUND(CAST(month_3 AS FLOAT) / NULLIF(count, 0),3) AS month_3_density,
    ROUND(CAST(month_4 AS FLOAT) / NULLIF(count, 0),3) AS month_4_density,
    ROUND(CAST(month_5 AS FLOAT) / NULLIF(count, 0),3) AS month_5_density,
    ROUND(CAST(month_6 AS FLOAT) / NULLIF(count, 0),3) AS month_6_density,
    ROUND(CAST(month_7 AS FLOAT) / NULLIF(count, 0),3) AS month_7_density,
    ROUND(CAST(month_8 AS FLOAT) / NULLIF(count, 0),3) AS month_8_density,
    ROUND(CAST(month_9 AS FLOAT) / NULLIF(count, 0),3) AS month_9_density,
    ROUND(CAST(month_10 AS FLOAT) / NULLIF(count, 0),3) AS month_10_density,
    ROUND(CAST(month_11 AS FLOAT) / NULLIF(count, 0),3) AS month_11_density,
    ROUND(CAST(month_12 AS FLOAT) / NULLIF(count, 0),3) AS month_12_density,
    month_1,
    month_2,
    month_3,
    month_4,
    month_5,
    month_6,
    month_7,
    month_8,
    month_9,
    month_10,
    month_11,
    month_12
FROM clean.inat_phenology 
ORDER BY taxonID, attribute_label, value_label